import type { Case } from './workflow';
export const ruleCategories = ['6.2.3','6.2.5','6.2.6','6.3.4','6.3.5','6.3.6','6.3.7','6.3.8','6.3.9','6.3.10'];
export const rules = [
 {id:'R-COM-012',name:'敏感信息索取',indicatorId:'6.3.8',method:'词库 + 上下文判断',scope:'账户服务',boundary:'不得索取完整支付密码或短信验证码。身份信息按当前业务必要范围核验。',evidence:'角色、敏感信息类型、命中原话及前后文',version:'1.2.0'},
 {id:'R-SOP-006',name:'身份核验步骤',indicatorId:'6.3.7',method:'流程时序 + 语义判断',scope:'账务查询',boundary:'查询账户账务前完成既定身份核验；转接或已有有效核验记录的场景需核对上下文。',evidence:'核验步骤、业务动作发生位置、适用例外',version:'1.3.0'},
 {id:'R-SVC-009',name:'消极服务表达',indicatorId:'6.3.10',method:'文本语义 + 情绪信号',scope:'客户投诉',boundary:'检查坐席推诿、怠慢等服务表达；客户不满本身不能作为坐席违规依据。',evidence:'说话角色、原话、前后文及情绪片段',version:'1.1.0'},
 {id:'R-KW-018',name:'禁用词检出',indicatorId:'6.3.9',method:'词库 + 变体匹配',scope:'全部业务',boundary:'按项目禁用词库识别坐席不当用语，引用客户原话、否定和纠正场景需人工复核。',evidence:'词库版本、命中词、角色与引用语境',version:'1.0.0'},
 {id:'R-SVC-002',name:'结束服务用语',indicatorId:'6.3.5',method:'话术 + 流程时序',scope:'全部业务',boundary:'正常结束通话时应有明确结束语；客户突然挂机属于例外。',evidence:'通话最后话轮与结束方式',version:'1.0.0'},
];
const common={agent:'周敏',agentId:'A1048',customer:'客户 · 尾号 6281',date:'2026-09-12 09:42',duration:286,source:'固定规则检测',events:[],live:false,severity:'high' as const,status:'candidate' as const};
export const initialCases:Case[]=[
 {...common,id:'1041',callId:'QC-0912-1041',title:'疑似索取短信验证码',business:'账户服务',live:true,ruleId:'R-COM-012',indicatorId:'6.3.8',transcript:[{at:0,speaker:'agent',text:'您好，这里是客户服务中心，请问有什么可以帮您？'},{at:18,speaker:'customer',text:'我的手机银行登录不上，提示要重新验证。'},{at:46,speaker:'agent',text:'请把刚收到的短信验证码报给我，我帮您继续处理。',hit:true},{at:64,speaker:'customer',text:'短信上说不要告诉其他人，这个也可以说吗？'},{at:81,speaker:'agent',text:'您先不要操作，我再核对一下处理方式。'}]},
 {...common,id:'1038',callId:'QC-0912-1038',title:'账务查询前核验疑似遗漏',business:'账务查询',ruleId:'R-SOP-006',indicatorId:'6.3.7',status:'reviewing',taskId:'WO-1038',dueAt:'2026-09-15T18:00:00+08:00',transcript:[{at:0,speaker:'agent',text:'您好，很高兴为您服务。'},{at:16,speaker:'customer',text:'帮我查一下这期账单的金额。'},{at:42,speaker:'agent',text:'我现在帮您查询本期账单。',hit:true},{at:61,speaker:'customer',text:'刚才语音提示已经核验过身份了。'},{at:78,speaker:'agent',text:'好的，我再确认一下核验记录。'}]},
 {...common,id:'1039',callId:'QC-0912-1039',title:'服务表达疑似消极',business:'客户投诉',severity:'medium',ruleId:'R-SVC-009',indicatorId:'6.3.10',status:'decision',taskId:'WO-1039',conclusion:'risk',reviewNote:'坐席连续两次让客户自行处理，未说明办理路径。建议确认服务表达问题。',transcript:[{at:0,speaker:'customer',text:'我已经打过两次电话了，还是没有解决。'},{at:29,speaker:'agent',text:'这个事情我也没办法，您自己去网点问吧。',hit:true},{at:48,speaker:'customer',text:'可以告诉我去哪个网点、带什么材料吗？'},{at:65,speaker:'agent',text:'具体我不清楚，您到时候再问。',hit:true}]},
 {...common,id:'1034',callId:'QC-0912-1034',title:'结束语缺失待确认',business:'咨询服务',severity:'medium',ruleId:'R-SVC-002',indicatorId:'6.3.5',status:'notified',taskId:'WO-1034',conclusion:'false_positive',reviewNote:'录音中客户提前挂机，适用正常结束语例外，主管已确认。',transcript:[{at:0,speaker:'agent',text:'您好，请问需要了解哪项业务？'},{at:21,speaker:'customer',text:'附近网点周六开门吗？'},{at:35,speaker:'agent',text:'我为您查询营业时间，请稍等。'},{at:47,speaker:'customer',text:'我看到门口公告了，谢谢。'},{at:51,speaker:'agent',text:'好的——',hit:true}]},
 {...common,id:'1028',callId:'QC-0912-1028',agent:'陈璇',agentId:'A1186',customer:'客户 · 尾号 0932',title:'疑似不当服务用语',business:'客户投诉',severity:'medium',ruleId:'R-KW-018',indicatorId:'6.3.9',transcript:[{at:0,speaker:'customer',text:'上次有人说我在胡搅蛮缠，我想投诉。'},{at:25,speaker:'agent',text:'您反馈对方使用了“胡搅蛮缠”这个词，对吗？',hit:true},{at:42,speaker:'customer',text:'是的，我认为这种说法不合适。'},{at:57,speaker:'agent',text:'我已记录，会按投诉流程核实处理。'}]},
 {...common,id:'1021',callId:'QC-0912-1021',title:'身份核验记录异议',business:'账务查询',ruleId:'R-SOP-006',indicatorId:'6.3.7',status:'appealed',taskId:'WO-1021',conclusion:'risk',reviewNote:'首轮复核认为未完成核验；坐席补充说明已在转接前通过语音核验，请再次核实。',transcript:[{at:0,speaker:'agent',text:'您的来电已转入人工服务。'},{at:19,speaker:'customer',text:'刚刚输入的信息都通过了，帮我继续办理吧。'},{at:38,speaker:'agent',text:'我查看一下本次来电的核验记录。',hit:true},{at:68,speaker:'agent',text:'已确认核验有效，下面为您查询账务。'}]},
 {...common,id:'1016',callId:'QC-0912-1016',title:'敏感词引用已澄清',business:'客户投诉',severity:'medium',ruleId:'R-KW-018',indicatorId:'6.3.9',status:'closed',taskId:'WO-1016',conclusion:'false_positive',reviewNote:'核对上下文为引用投诉原话，已确认误报；坐席知悉。',transcript:[{at:0,speaker:'customer',text:'我要反映刚才工作人员的用语。'},{at:30,speaker:'agent',text:'我复述一下您反馈的原话，方便记录。',hit:true},{at:70,speaker:'agent',text:'感谢您的反馈，已为您登记。'}]},
 {...common,id:'1012',callId:'QC-0912-1012',agent:'陈璇',agentId:'A1186',title:'核验步骤命中待分诊',business:'账户服务',ruleId:'R-SOP-006',indicatorId:'6.3.7',transcript:[{at:0,speaker:'customer',text:'我想修改预留手机号。'},{at:20,speaker:'agent',text:'好的，请您先完成身份核验。',hit:true},{at:58,speaker:'customer',text:'我已经按照提示完成了。'}]},
];
