import test from "node:test";
import assert from "node:assert/strict";
import {createInitial} from "../lib/fixtures.ts";
import {apply,entity,actions} from "../lib/workflow.ts";
import {pendingResourceRules} from "../lib/resource-publication.ts";
const now=new Date("2026-09-20T10:00:00+08:00");let n=0;
const command=(s,id,action,input={})=>({id,action,input:{note:"核对资源与规则引用后提交",...input},rev:entity(s,id).rev,requestId:`publication-${++n}`});
const run=(s,id,action,input)=>apply(s,command(s,id,action,input),now);
function published(){let s=createInitial(now);s=run(s,"RES-WORD","save_resource",{content:"完整验证码\n银行密码",scope:"全部业务",resourceRole:"坐席",exception:"排除否定语境"});s=run(s,"RES-WORD","check_resource",{checkPass:true});return run(s,"RES-WORD","publish_resource");}
test("P01: publishing only creates a resource version; all rule and detection snapshots remain unchanged",()=>{const initial=createInitial(now),s=published();assert.equal(entity(s,"RES-WORD").versions.length,2);assert.deepEqual(s.rules,initial.rules);assert.deepEqual(s.calls,initial.calls);assert.deepEqual(s.findings,initial.findings);});
test("P02: selected reference adoption is versioned, scoped, logged and idempotent",()=>{const s=published(),id="R-COM-012",cmd=command(s,"RES-WORD","switch_resource",{refs:[id],referenceRevs:{[id]:entity(s,id).rev}}),next=apply(s,cmd,now);assert.equal(entity(next,id).versions.at(-1).resources["RES-WORD"],2);assert.equal(entity(next,id).versions[0].resources["RES-WORD"],1);assert.deepEqual(next.rules.filter(r=>r.id!==id),s.rules.filter(r=>r.id!==id));assert.deepEqual(next.calls,s.calls);assert.ok(next.logs.some(log=>log.target===id && log.action==="切换资源引用"));assert.deepEqual(apply(next,cmd,now),next);});
test("P03: stale rule revision and empty selection reject without changing any snapshot",()=>{const s=published(),before=structuredClone(s);assert.throws(()=>run(s,"RES-WORD","switch_resource",{refs:["R-COM-012"],referenceRevs:{"R-COM-012":999}}),/关联规则已更新/);assert.throws(()=>run(s,"RES-WORD","switch_resource",{refs:[]}),/请选择/);assert.deepEqual(s,before);});
test("P04: one drafted rule blocks the whole multi-rule transaction",()=>{const s=published(),rules=pendingResourceRules(s,entity(s,"RES-WORD"));assert.ok(rules.length>1);rules[1].draft=structuredClone(rules[1].versions.at(-1));const before=structuredClone(s);assert.throws(()=>run(s,"RES-WORD","switch_resource",{refs:rules.slice(0,2).map(r=>r.id),referenceRevs:Object.fromEntries(rules.map(r=>[r.id,r.rev]))}),/存在参数草稿/);assert.deepEqual(s,before);});
test("P05: read-only roles cannot adopt references and stale resource forms fail",()=>{const s=published();for(const identity of ["Q01","A1048"]){const restricted={...s,identity};assert.ok(!actions(restricted,"RES-WORD").includes("switch_resource"));assert.throws(()=>run(restricted,"RES-WORD","switch_resource",{refs:["R-COM-012"]}),/不允许|无权/);}const cmd=command(s,"RES-WORD","switch_resource",{refs:["R-COM-012"]});cmd.rev--;assert.throws(()=>apply(s,cmd,now),/更新|变化|刷新/);});
